In [2]:
import numpy as np

In [3]:
range_arr1=np.arange(12)
range_arr2=np.arange(0,12)
range_arr3=np.arange(0,12,2)

In [4]:
print(range_arr1)
print(range_arr2)
print(range_arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10]


In [12]:
lin1=np.linspace(0,1) # Automates to 50
lin2=np.linspace(0,1,5)
## lin3=np.linspace(12) -- invalid

In [14]:
print(lin1)
print(lin2)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
[0.   0.25 0.5  0.75 1.  ]


In [15]:
# Random
random_arr = np.random.rand(3, 3)  # Uniform [0, 1)
print(random_arr)

random_int = np.random.randint(0, 10, (3, 3))  # Random integers
print(random_int)

# Normal distribution
normal = np.random.normal(0, 1, (3, 3))  # Mean=0, Std=1
print(normal)

[[0.87535823 0.26085247 0.26903754]
 [0.78120179 0.77735688 0.28788231]
 [0.53947034 0.74445164 0.23008764]]
[[3 7 9]
 [2 1 9]
 [1 4 8]]
[[-1.0426439   0.33570504  1.45440101]
 [-1.55930709 -1.74451619 -0.69749643]
 [-1.17468688 -0.65174719 -1.18407488]]


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr.sum())
print(arr.max())
print(arr.min())

print(arr.mean())

print(arr.var()) # variance= sum of  (each number - mean)^2
print(arr.std()) # standard deviation= sqrt of variance


print(arr.argmin()) # the index where min/max occurs
print(arr.argmax())


arr2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr2d.sum(axis=0)) # Sum along column
print(arr2d.sum(axis=1)) # Sum along row

print(arr2d.mean(axis=0)) #mean along column


print(arr2d.sum()) # All sum

15
5
1
3.0
2.0
1.4142135623730951
0
4
[ 7  9 11 13 15]
[15 40]
[3.5 4.5 5.5 6.5 7.5]
55


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Slicing creates a view
view = arr[1:4]
print(view)  # Output: [2 3 4]

# Modify the view
view[0] = 99
print(view)  # Output: [99 3 4]
print(arr)   # Output: [1 99 3 4 5] - Original changed!

# Check if it's a view
print(view.base is arr)  # Output: True (shares memory)
print(arr.base is view)  # False
print(arr.base is arr)   # False
print(arr.base is None)  # True

[2 3 4]
[99  3  4]
[ 1 99  3  4  5]
True
False
False
True


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# These create VIEWS (shallow copy)
view1 = arr[:]           # Slice
print(view1)
view2 = arr[1:, :]        # Slice
print(view2)
view3 = arr.ravel()
print(view3)       # Ravel (usually)
view4 = arr.T             # Transpose
print(view4)

# These create COPIES (deep copy)
copy1 = arr.copy()        # Explicit copy
copy2 = arr.reshape(3, 2)  # Reshape (usually)
copy3 = arr.flatten()      # Flatten

# Check with base attribute
print(view1.base is arr)   # True (view)
print(copy1.base is None)  # True (copy)

[[1 2 3]
 [4 5 6]]
[[4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
True
True
